# Generated by Django 5.2.6 on 2025-10-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='rooms_available',
            field=models.IntegerField(default=20),
        ),
    ]
