# Generated by Django 5.2.6 on 2025-10-12 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_hotel_rooms_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busroute',
            name='seats_available',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='rooms_available',
        ),
        migrations.CreateModel(
            name='BusRouteAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('seats_available', models.IntegerField(default=40)),
                ('bus_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='travel.busroute')),
            ],
            options={
                'unique_together': {('bus_route', 'date')},
            },
        ),
        migrations.CreateModel(
            name='HotelAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('rooms_available', models.IntegerField(default=20)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='travel.hotel')),
            ],
            options={
                'unique_together': {('hotel', 'date')},
            },
        ),
    ]
