# Generated by Django 5.2.6 on 2025-10-12 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_remove_busroute_seats_available_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hotelavailability',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='hotelavailability',
            name='hotel',
        ),
        migrations.AddField(
            model_name='busroute',
            name='seats_available',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='rooms_available',
            field=models.IntegerField(default=20),
        ),
        migrations.DeleteModel(
            name='BusRouteAvailability',
        ),
        migrations.DeleteModel(
            name='HotelAvailability',
        ),
    ]
