# Generated by Django 5.2.6 on 2025-10-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_alter_hotelavailability_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='busroute',
            name='seats_available',
            field=models.IntegerField(default=40),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='rooms_available',
            field=models.IntegerField(default=10),
        ),
    ]
